os: linux
dist: xenial
language: python
python:
- "3.8.1"

arch:
- amd64
- arm64

install:
- pip install -U -r requirements.txt
- pip install -U pyinstaller

before_script:
- if [ $TRAVIS_CPU_ARCH == 'arm64' ]; then
    export BINARY_NAME=supervisor-arm64;
  else
    export BINARY_NAME=supervisor;
  fi;

script:
- python -m unittest discover -s test/unit/faassupervisor -p '*.py'
- pyinstaller --onefile -n $BINARY_NAME faassupervisor/supervisor.py

deploy:
  - provider: releases
    token: $GITHUB_OAUTH_TOKEN
    file: dist/$BINARY_NAME
    skip_cleanup: true
    on:
      tags: true

jobs:
  include:
  - stage: Deploy to PyPi on new releases
    script: skip
    arch: amd64
    deploy:
      - provider: pypi
        username: $PYPI_USER
        password: $PYPI_PASS
        on:
          tags: true
    if: tag IS present